# Generated by Django 3.1.7 on 2021-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterType', models.CharField(max_length=50, verbose_name='Черта характера')),
            ],
            options={
                'verbose_name': 'Черта характера',
                'verbose_name_plural': 'Черта характера',
            },
        ),
        migrations.AlterModelOptions(
            name='deals',
            options={'ordering': ['date'], 'verbose_name': 'Заявка на покупку', 'verbose_name_plural': 'Заявки на покупку'},
        ),
        migrations.RemoveField(
            model_name='dogs',
            name='dogClass',
        ),
        migrations.AlterField(
            model_name='dogs',
            name='age',
            field=models.FloatField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dogName',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.DeleteModel(
            name='DogClasses',
        ),
        migrations.AddField(
            model_name='dogs',
            name='character',
            field=models.ManyToManyField(blank=True, to='blog.Characters', verbose_name='Классификация'),
        ),
    ]
